artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/4fb2a138d57b455fb3cb1fb4666fe7a2/artifacts
end_time: 1756393856299
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 4fb2a138d57b455fb3cb1fb4666fe7a2
run_name: Default
run_uuid: 4fb2a138d57b455fb3cb1fb4666fe7a2
source_name: ''
source_type: 4
source_version: ''
start_time: 1756393856288
status: 3
tags: []
user_id: mle-user
