artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/dbbdc0e5c2b64225ba790cf766fc35e5/artifacts
end_time: 1756291512989
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: dbbdc0e5c2b64225ba790cf766fc35e5
run_name: Default
run_uuid: dbbdc0e5c2b64225ba790cf766fc35e5
source_name: ''
source_type: 4
source_version: ''
start_time: 1756291512981
status: 3
tags: []
user_id: mle-user
