artifact_location: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/491892429858549463
creation_time: 1756294920832
experiment_id: '491892429858549463'
last_update_time: 1756294920832
lifecycle_stage: active
name: test_connection_experiment_vadim_shakula
