artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/d98b3046d5bb42fd89fc5ab0badf4368/artifacts
end_time: 1756291657794
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: d98b3046d5bb42fd89fc5ab0badf4368
run_name: Default
run_uuid: d98b3046d5bb42fd89fc5ab0badf4368
source_name: ''
source_type: 4
source_version: ''
start_time: 1756291657786
status: 3
tags: []
user_id: mle-user
