artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/a256b64d73194adebfa047091b5ea2f8/artifacts
end_time: 1756141415148
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: a256b64d73194adebfa047091b5ea2f8
run_name: Default
run_uuid: a256b64d73194adebfa047091b5ea2f8
source_name: ''
source_type: 4
source_version: ''
start_time: 1756141415135
status: 3
tags: []
user_id: mle-user
