artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/491892429858549463/8dd8a2aa2d5543069e7c3b5fb9c1ffc3/artifacts
end_time: 1756295022897
entry_point_name: ''
experiment_id: '491892429858549463'
lifecycle_stage: active
run_id: 8dd8a2aa2d5543069e7c3b5fb9c1ffc3
run_name: test_connection_run
run_uuid: 8dd8a2aa2d5543069e7c3b5fb9c1ffc3
source_name: ''
source_type: 4
source_version: ''
start_time: 1756295022869
status: 3
tags: []
user_id: mle-user
