artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/593aa72a25204247927fd81db4242e28/artifacts
end_time: 1756412948891
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 593aa72a25204247927fd81db4242e28
run_name: Default
run_uuid: 593aa72a25204247927fd81db4242e28
source_name: ''
source_type: 4
source_version: ''
start_time: 1756412948839
status: 3
tags: []
user_id: mle-user
